<?php
namespace VuDacKyAnh\Test\Ui\Component\Listing\Column;

use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;
use Magento\Framework\UrlInterface;
use Magento\Store\Model\StoreManagerInterface;

class Phone extends \Magento\Ui\Component\Listing\Columns\Column
{

    protected $_storeManger;
    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        StoreManagerInterface $storemanager,
        array $components = [],
        array $data = []
    ) {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->_storeManager = $storemanager;
    }

    public function prepareDataSource(array $dataSource)
    {

        if (isset($dataSource['data']['items'])) {

            foreach ($dataSource['data']['items'] as & $item){
                $fieldName=$this->getData('name');
                $rating='';
                $loop=$item['phone'];
                    $rating.="+84". +$loop;
                $item[$fieldName]=$rating;


            }
        }

        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}